amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.02 
    alpha2: 0.1  # Consider reducing if overshooting is related to rotational movements
    alpha3: 0.05  # Further reduced to decrease translational motion noise
    alpha4: 0.25  # Increased for rotational motion noise
    alpha5: 0.1
    base_frame_id: "base_link"
    beam_skip_distance: 3.0 #try not to skip beams
    beam_skip_error_threshold: 0.3
    beam_skip_threshold: 0.9
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 1.5
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 300
    max_particles: 5000  
    min_particles: 250
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"  
    save_pose_rate: 0.05
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.01 
    update_min_d: 0.01  
    z_hit: 0.6
    z_max: 0.05
    z_rand: 0.4
    z_short: 0.05
